global_frame: odom
rolling_window: true
track_unknown_space: false
width: 5
height: 5

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
