footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
footprint_padding: 0.1
robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 2.0
transform_tolerance: 1.0
publish_voxel_map: false
resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0
static:
    map_topic: map
    subscribe_to_updates: true
    lethal_cost_threshold: 50

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan_filtered, inf_is_valid: false}

inflation:
  inflation_radius: 1.0
  cost_scaling_factor: 2.0
