controller_frequency: 5.0
controller_patience: 10.0
planner_frequency: 0.5
planner_patience: 10.0
shutdown_costmaps: false
oscillation_distance: 0.2
oscillation_timeout: 10.0
conservative_reset_dist: 0.2
cost_factor: 1.0
neutral_cost: 55
lethal_cost: 253

recovery_behaviour_enabled: true
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}] 

DWAPlannerROS:
  acc_lim_x: 0.5
  acc_limit_trans: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.5

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 0.6
  min_rot_vel: 0.2
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.2
  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: true

  sim_time: 1.5
  sim_granularity: 0.03
  angular_sim_granularity: 0.05
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20

  penalize_negative_x: true
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.1
  forward_point_distance: 0.6
  stop_time_buffer: 0.2
  scaling_speed: 0.1
  control_frequency: 10.0
  max_scaling_factor: 0.1

  oscillation_reset_dist: 0.1
  oscillation_reset_angle: 0.1

  prune_plan: true
  use_dwa: true
